package org.omg.PortableServer;


/**
* org/omg/PortableServer/IMPLICIT_ACTIVATION_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from d:/re/workspace/8-2-build-windows-i586-cygwin/jdk8u20/1074/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Wednesday, July 30, 2014 6:15:47 PM PDT
*/

public interface IMPLICIT_ACTIVATION_POLICY_ID
{

  /**
	 * The value representing IMPLICIT_ACTIVATION_POLICY_ID.
	 */
  public static final int value = (int)(20L);
}
