package org.omg.PortableServer;


/**
* org/omg/PortableServer/LifespanPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from d:/re/workspace/8-2-build-windows-i586-cygwin/jdk8u20/1074/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Wednesday, July 30, 2014 6:15:47 PM PDT
*/


/**
	 * The LifespanPolicy specifies the lifespan of the 
	 * objects implemented in the created POA. The default 
	 * is TRANSIENT.
	 */
public interface LifespanPolicy extends LifespanPolicyOperations, org.omg.CORBA.Policy, org.omg.CORBA.portable.IDLEntity 
{
} // interface LifespanPolicy
