package org.omg.IOP;


/**
* org/omg/IOP/TransactionService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from d:/re/workspace/8-2-build-windows-i586-cygwin/jdk8u20/1074/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Wednesday, July 30, 2014 6:15:47 PM PDT
*/

public interface TransactionService
{

  /**
     * Identifies a CDR encapsulation of the 
     * <code>CosTSInteroperation.PropogationContext</code> defined in 
     * <i>CORBAservices: Common Object Services Specifications.</i>
     */
  public static final int value = (int)(0L);
}
